services:
    kwik-mq:
        build: .
        env_file:
            - .env
        ports:
            - '10526:10526'
        volumes:
            - ./data:/app/data
        environment:
            - DATA_DIR=/app/data
        deploy:
            restart_policy:
                condition: always
        user: '1000:1000'
        stop_grace_period: 30s
        healthcheck:
            test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:10526/health']
            interval: 30s
            timeout: 10s
            retries: 3
